# Hyperparameters for iterations of data generation
Iterations_Avatar_Location_Randomization: 5
Iterations_Lighting_Randomization: 5
Number_of_Image_Sequences: 100

# Hyperparameters for scene setup
Camera_Radius: 3
Number_of_Workers: 6
 
# Hyperparameters for rendering type
Drone_View: False

# Hyperparameters for rendering settings
max_bounces: 4                      # Sets the maximum number of light bounces for ray tracing, affecting the realism and computational load.
samples: 1024                       # Sets the number of samples per pixel for rendering, affecting image quality and render time.
tile_size: 256                     # Defines the size of render tiles, impacting render efficiency. 
adaptive_threshold: 0.001           # Sets the threshold for adaptive sampling, improving efficiency by reducing samples in areas with less noise.
resolution_x: 1024                  # Sets the horizontal resolution of the render to 1920 pixels.
resolution_y: 1024                  # Sets the vertical resolution of the render to 1920 pixels.
Framerate: 100                     # Sets the frames per second for the animation, and the number of frames to skip for each step in animation playback.
